In [56]:
#Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import RANSACRegressor, HuberRegressor
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.metrics import confusion_matrix
from eval_scores import scores

In [57]:
#Extract data
X = np.load('Xtrain_Regression_Part2.npy')
y = np.load('Ytrain_Regression_Part2.npy')

ransac = RANSACRegressor()

cross_val = cross_validate(ransac, X, y, cv = 3)
sorted(cross_val.keys())
cross_val['test_score']

array([0.99823806, 0.99742259, 0.43452122])

In [58]:
scores = cross_validate(ransac, X, y, cv=3, scoring=('r2', 'neg_mean_squared_error'), return_train_score=True)

print(scores['test_neg_mean_squared_error'])

[-0.01557366 -0.02457909 -4.9771076 ]


In [59]:
print(scores['train_r2'])

[0.73101064 0.71746778 0.99905829]


In [60]:
huber = HuberRegressor()

cross_hub = cross_validate(huber, X, y, cv = 3)
sorted(cross_hub.keys())
cross_hub['test_score']

/Users/karolineherleiksplass/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/karolineherleiksplass/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/karolineherleiksplass/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0.99799318, 0.99780101, 0.42795347])

In [61]:
scores = cross_validate(huber, X, y, cv=3, scoring=('r2', 'neg_mean_squared_error'), return_train_score=True)
print(scores['test_neg_mean_squared_error'])

[-0.01773816 -0.02097034 -5.03491424]


/Users/karolineherleiksplass/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/karolineherleiksplass/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/karolineherleiksplass/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [62]:
print(scores['train_r2'])

[0.7327244  0.72246225 0.99890819]
